# Dockerfile
FROM python:3.10

ENV CELERY_APP="make_celery"
ENV CELERY_OPTS="-P solo -B -E -s workdir/celerybeat-schedule"
ENV CELERY_LOGLEVEL="INFO"

# set fixed UID and GID - see github.com/hexops/dockerfile
ARG UID=10000
ARG GID=10001

RUN addgroup --gid ${GID} gaia
RUN adduser --uid ${UID} --disabled-password --home /app --shell /bin/sh --ingroup gaia celery



RUN apt update && \
    apt install -y python3-flask-bootstrap python3-flask python3-celery python3-sqlalchemy \
    python3-psycopg2 python3-owslib python3-jsonpickle python3-redis gunicorn && \
    apt clean

COPY ./requirements.txt /

RUN pip install -r requirements.txt

RUN mkdir /geordash
RUN chown celery:gaia /geordash

USER celery

COPY . /geordash
WORKDIR /geordash

CMD ["sh", "-c", "celery -A make_celery worker --loglevel INFO -P solo -B -E -s workdir/celerybeat-schedule -s celerybeat-schedule"]